'use client';

import React from 'react';
import { useState, useEffect, useRef } from 'react';
import { useForm, FormProvider } from 'react-hook-form';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { AlertCircle, Loader2, User, Building2, FileCheck, ArrowLeft } from 'lucide-react';
import Submitted from './submitted';
import { fetchIfsc } from '@/hooks/fetchIfscHook';
import { usePostAgent, type OnboardingFormValues, type RegisterAgentData } from '@/hooks/usePostAgent';
import { useRouter } from 'next/navigation';
import FileUploadController from './useForm/FileController';

export type { OnboardingFormValues };

const defaultValues: OnboardingFormValues = {
  name: '',
  email: '',
  phoneNumber: '',
  dob: '',
  accountHolderName: '',
  bankName: '',
  accountNumber: '',
  ifscCode: '',
  accountType: 'SAVINGS',
  branchName: '',
  idType: 'PAN',
  idDocument: null,
};

export default function OnboardingForm() {
  const router = useRouter();
  const { register: registerAgent, isPending, error: registerError, reset: resetRegister } = usePostAgent();
  const [submitted, setSubmitted] = useState(false);
  const [applicationId, setApplicationId] = useState('');
  const [ifscLoading, setIfscLoading] = useState(false);
  const [ifscError, setIfscError] = useState<string | null>(null);
  const [branchAddress, setBranchAddress] = useState<string | null>(null);
  const ifscFetchedRef = useRef<string | null>(null);

  const methods = useForm<OnboardingFormValues>({
    defaultValues,
    mode: 'onBlur',
  });

  const {
    handleSubmit: rhfHandleSubmit,
    watch,
    setValue,
    reset,
    clearErrors,
    formState: { errors },
  } = methods;

  const ifscCode = watch('ifscCode');

  const onSubmit = async (data: OnboardingFormValues) => {
    if (!data.idDocument?.url?.trim()) {
      setValue('idDocument', data.idDocument ?? { name: '', url: '' });
      methods.setError('idDocument', {
        type: 'manual',
        message: 'Please upload your ID document. The file link (GCP/S3) is required before submitting.',
      });
      return;
    }
    resetRegister();
    const response = await registerAgent(data);
    if (!response) {
      return;
    }
    // Application id is auto-generated by the backend (MongoDB _id).
    const appId = (response as RegisterAgentData).applicationId ?? '';
    setApplicationId(appId);
    setSubmitted(true);

  
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    const nextValue = name === 'ifscCode' ? value.toUpperCase().replace(/\s/g, '') : value;
    if (name === 'ifscCode') {
      setBranchAddress(null);
      setIfscError(null);
      ifscFetchedRef.current = null;
    }
    setValue(name as keyof OnboardingFormValues, nextValue);
  };

  // Fetch bank details from Razorpay IFSC API when user enters 11-character IFSC
  useEffect(() => {
    const code = ifscCode?.trim().toUpperCase() || '';
    if (code.length !== 11 || code === ifscFetchedRef.current) {
      if (code.length !== 11) {
        setBranchAddress(null);
        setIfscError(null);
      }
      return;
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
      setIfscLoading(true);
      fetchIfsc({
        code,
        controller,
        setIfscLoading,
        setIfscError,
        setBranchAddress,
        ifscFetchedRef,
        onSuccess: (data) => {
          setValue('bankName', data.BANK);
          setValue('branchName', data.BRANCH);
        },
        onClearErrors: (fields) => clearErrors(fields as (keyof OnboardingFormValues)[]),
      });
    }, 400);

    return () => {
      clearTimeout(timeoutId);
      controller.abort();
    };
  }, [ifscCode, setValue, clearErrors]);


  if (submitted) {
    return <Submitted applicationId={applicationId} />;
  }

  return (
    <FormProvider {...methods}>
      <div className="mx-auto max-w-3xl px-4 py-6 md:py-10">
        {/* Form header */}
        <header className="mb-8 md:mb-10">
          <div className="flex items-center gap-2">
            <ArrowLeft className="cursor-pointer" onClick={() => router.back()} />
            <h2 className="text-2xl font-bold tracking-tight text-foreground md:text-3xl">
              Partner Registration
            </h2>
          </div>
          <p className="mt-2 text-sm text-muted-foreground">
            Complete all sections below. Fields marked with * are required.
          </p>
        </header>

        <form onSubmit={rhfHandleSubmit(onSubmit)} className="space-y-8">
        {/* Personal Information */}
        <Card className="overflow-hidden border-amber-200/50 border-l-4 border-l-primary/60 bg-linear-to-br from-white to-amber-50/30 shadow-sm">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3">
              <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <User className="size-5" />
              </div>
              <div>
                <CardTitle className="text-lg">Personal Information</CardTitle>
                <CardDescription>Provide your basic personal details</CardDescription>
              </div>
            </div>
          </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid gap-6 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="name">Full Name *</Label>
              <Input
                id="name"
                placeholder="Agent Name"
                className={errors.name ? 'border-destructive' : ''}
                {...methods.register('name', { required: 'Name is required' })}
              />
              {errors.name && (
                <p className="text-sm text-destructive">{errors.name.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email Address *</Label>
              <Input
                id="email"
                type="email"
                placeholder="agent@example.com"
                className={errors.email ? 'border-destructive' : ''}
                {...methods.register('email', {
                  required: 'Email is required',
                  pattern: {
                    value: /\S+@\S+\.\S+/,
                    message: 'Email is invalid',
                  },
                })}
              />
              {errors.email && (
                <p className="text-sm text-destructive">{errors.email.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="phoneNumber">Phone Number *</Label>
              <div
                className={`flex rounded-md border border-input bg-background ring-offset-background has-[:focus-visible]:outline-none has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-ring has-[:focus-visible]:ring-offset-2 ${errors.phoneNumber ? 'border-destructive' : ''}`}
              >
                <span className="inline-flex items-center px-3 text-muted-foreground border-r border-input">
                  +91
                </span>
                <Input
                  id="phoneNumber"
                  value={
                    watch('phoneNumber')?.startsWith('+91')
                      ? watch('phoneNumber').slice(3).trimStart()
                      : watch('phoneNumber') || ''
                  }
                  onChange={(e) => {
                    const value = e.target.value.replace(/\D/g, '');
                    setValue('phoneNumber', value ? `+91 ${value}` : '');
                  }}
                  placeholder="98XXXXXXXX"
                  className="border-0 focus-visible:ring-0 focus-visible:ring-offset-0 rounded-l-none"
                />
              </div>
              {errors.phoneNumber && (
                <p className="text-sm text-destructive">{errors.phoneNumber.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="dob">Date of Birth *</Label>
              <Input
                id="dob"
                type="date"
                className={errors.dob ? 'border-destructive' : ''}
                {...methods.register('dob', { required: 'Date of birth is required' })}
              />
              {errors.dob && (
                <p className="text-sm text-destructive">{errors.dob.message}</p>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

        {/* Bank Details */}
        <Card className="overflow-hidden border-amber-200/50 border-l-4 border-l-primary/60 bg-linear-to-br from-white to-amber-50/30 shadow-sm">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3">
              <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Building2 className="size-5" />
              </div>
              <div>
                <CardTitle className="text-lg">Bank Account Details</CardTitle>
                <CardDescription>Provide your bank account information for payments</CardDescription>
              </div>
            </div>
          </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid gap-6 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="accountNumber">Account Number *</Label>
              <Input
                id="accountNumber"
                placeholder="Account number"
                className={errors.accountNumber ? 'border-destructive' : ''}
                {...methods.register('accountNumber', {
                  required: 'Account number is required',
                })}
              />
              {errors.accountNumber && (
                <p className="text-sm text-destructive">{errors.accountNumber.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="accountHolderName">Account Holder Name *</Label>
              <Input
                id="accountHolderName"
                placeholder="Name as per bank records"
                className={errors.accountHolderName ? 'border-destructive' : ''}
                {...methods.register('accountHolderName', {
                  required: 'Account holder name is required',
                })}
              />
              {errors.accountHolderName && (
                <p className="text-sm text-destructive">{errors.accountHolderName.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="ifscCode">IFSC Code *</Label>
              <div className="relative">
                <Input
                  id="ifscCode"
                  name="ifscCode"
                  value={watch('ifscCode') || ''}
                  onChange={handleInputChange}
                  placeholder="e.g. KKBK0007816"
                  maxLength={11}
                  className={`pr-9 ${errors.ifscCode ? 'border-destructive' : ''} ${ifscLoading ? 'border-primary/50' : ''}`}
                />
                {ifscLoading && (
                  <span className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                    <Loader2 className="h-4 w-4 animate-spin" />
                  </span>
                )}
              </div>
              {ifscError && (
                <p className="text-sm text-destructive flex items-center gap-1.5">
                  <AlertCircle className="h-4 w-4 shrink-0" />
                  {ifscError}
                </p>
              )}
              {branchAddress && !ifscLoading && (
                <p className="text-xs text-muted-foreground bg-muted/50 rounded-md px-3 py-2 border border-border/50">
                  <span className="font-medium text-foreground">Branch address: </span>
                  {branchAddress}
                </p>
              )}
              {errors.ifscCode && (
                <p className="text-sm text-destructive">{errors.ifscCode.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="bankName">Bank Name *</Label>
              <Input
                id="bankName"
                placeholder="State Bank of India"
                className={errors.bankName ? 'border-destructive' : ''}
                {...methods.register('bankName', { required: 'Bank name is required' })}
              />
              {errors.bankName && (
                <p className="text-sm text-destructive">{errors.bankName.message}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="accountType">Account Type *</Label>
              <Select
                value={watch('accountType')}
                onValueChange={(value) => setValue('accountType', value)}
              >
                <SelectTrigger id="SelectAccountType" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="SAVINGS">Savings</SelectItem>
                  <SelectItem value="CURRENT">Current</SelectItem>
                  <SelectItem value="BUSINESS">Business</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="branchName">Branch Name *</Label>
              <Input
                id="branchName"
                placeholder="Branch name"
                className={errors.branchName ? 'border-destructive' : ''}
                {...methods.register('branchName', {
                  required: 'Branch name is required',
                })}
              />
              {errors.branchName && (
                <p className="text-sm text-destructive">{errors.branchName.message}</p>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

        {/* Government ID */}
        <Card className="overflow-hidden border-amber-200/50 border-l-4 border-l-primary/60 bg-linear-to-br from-white to-amber-50/30 shadow-sm">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3">
              <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <FileCheck className="size-5" />
              </div>
              <div>
                <CardTitle className="text-lg">Government ID Verification</CardTitle>
                <CardDescription>Upload your government-issued identification document</CardDescription>
              </div>
            </div>
          </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid gap-6 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="idType">ID Type *</Label>
              <Select
                value={watch('idType')}
                onValueChange={(value) => setValue('idType', value)}
              >
                <SelectTrigger id="idType" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="PAN">PAN Card</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <FileUploadController
                name="idDocument"
                label="Upload Document *"
               accept={['image/*', '.pdf']}
                maxSize={10 * 1024 * 1024}
                rules={{ required: 'Government ID document is required' }}
                meta={{
                  refId: `${ifscCode}-${Date.now()}`,
                  belongsTo: 'agent',
                }}
              />
            </div>
          </div>
          <div className="flex items-start gap-3 rounded-lg bg-muted/50 p-4">
            <AlertCircle className="mt-0.5 h-5 w-5 text-muted-foreground flex-shrink-0" />
            <p className="text-sm text-muted-foreground">
              Ensure all details match your government ID exactly. Any discrepancies may cause your application to be rejected.
            </p>
          </div>
        </CardContent>
      </Card>

        {registerError && (
          <div className="flex items-center gap-2 rounded-lg border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-destructive">
            <AlertCircle className="size-4 shrink-0" />
            <span>{registerError}</span>
          </div>
        )}

        {/* Submit area */}
        <div className="rounded-xl border border-border/80 bg-card/50 px-6 py-6 shadow-sm md:px-8">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-sm text-muted-foreground">
              Review your details before submitting. You can clear the form to start over.
            </p>
            <div className="flex gap-3">
              <Button
                type="button"
                variant="outline"
                className="min-w-[120px]"
                disabled={isPending}
                onClick={() => {
                  reset(defaultValues);
                  setBranchAddress(null);
                  setIfscError(null);
                  ifscFetchedRef.current = null;
                  resetRegister();
                }}
              >
                Clear Form
              </Button>
              <Button
                type="submit"
                disabled={isPending}
                className="min-w-[160px] bg-primary hover:bg-primary/90"
              >
                {isPending ? (
                  <>
                    <Loader2 className="mr-2 size-4 animate-spin" />
                    Submitting…
                  </>
                ) : (
                  'Submit Application'
                )}
              </Button>
            </div>
          </div>
        </div>
        </form>
      </div>
    </FormProvider>
  );
}
