'use client';

import { useState, useCallback } from 'react';
import axios from 'axios';

// const REGISTER_URL = 'http://localhost:5050/agents/register';
const REGISTER_URL = 'https://mgm-backend.vercel.app/agents/register';

/** Form shape from onboarding (flat fields). */
export interface OnboardingFormValues {
  name: string;
  email: string;
  phoneNumber: string;
  dob: string;
  accountHolderName: string;
  bankName: string;
  accountNumber: string;
  ifscCode: string;
  accountType: string;
  branchName: string;
  idType: string;
  idDocument: { name: string; url: string } | null;
}

/** API request body (nested). Application id is generated by the backend. */
export interface RegisterAgentRequestBody {
  name: string;
  email: string;
  phoneNumber: string;
  dob: string;
  bankDetails: {
    accountHolderName: string;
    bankName: string;
    accountNumber: string;
    ifscCode: string;
    accountType: string;
    branchName: string;
  };
  governmentId: {
    type: string;
    documentUrl: string;
  };
}

/** Agent record returned inside the API response (backend-generated id in `_id`). */
export interface RegisterAgentData {
  _id: string;
  name: string;
  email: string;
  phoneNumber: string;
  dob: string;
  bankDetails: RegisterAgentRequestBody['bankDetails'];
  governmentId: RegisterAgentRequestBody['governmentId'];
  status: string;
  isnewuser?: boolean;
  isadmin?: boolean;
  ispasswordchanged?: boolean;
  createdAt: string;
  updatedAt: string;
  __v?: number;
  applicationId: string;
}

/** Full API response: message + data. */
export interface RegisterAgentApiResponse {
  message: string;
  data: RegisterAgentData;
}

/** Maps onboarding form values to the register API body. No application id — backend generates it. */
export function toRegisterRequestBody(data: OnboardingFormValues): RegisterAgentRequestBody {
  return {
    name: data.name,
    email: data.email,
    phoneNumber: data.phoneNumber,
    dob: data.dob,
    bankDetails: {
      accountHolderName: data.accountHolderName,
      bankName: data.bankName,
      accountNumber: data.accountNumber,
      ifscCode: data.ifscCode,
      accountType: data.accountType,
      branchName: data.branchName,
    },
    governmentId: {
      type: data.idType,
      documentUrl: data.idDocument?.url ?? '',
    },
  };
}

export interface UsePostAgentReturn {
  register: (data: OnboardingFormValues) => Promise<RegisterAgentData | null>;
  isPending: boolean;
  error: string | null;
  data: RegisterAgentData | null;
  reset: () => void;
}

export function usePostAgent(): UsePostAgentReturn {
  const [isPending, setIsPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<RegisterAgentData | null>(null);

  const reset = useCallback(() => {
    setError(null);
    setData(null);
  }, []);

  const register = useCallback(async (formData: OnboardingFormValues): Promise<RegisterAgentData | null> => {
    setIsPending(true);
    setError(null);
    setData(null);

    try {
      const body = toRegisterRequestBody(formData);
      const response = await axios.post<RegisterAgentApiResponse>(REGISTER_URL, body, {
        headers: { 'Content-Type': 'application/json' },
      });
      const agentData = response.data.data;
      setData(agentData);
      return agentData;
    } catch (err) {
      const message = axios.isAxiosError(err)
        ? err.response?.data?.message ?? err.message ?? 'Registration failed'
        : err instanceof Error ? err.message : 'Registration failed';
      setError(message);
      return null;
    } finally {
      setIsPending(false);
    }
  }, []);

  return { register, isPending, error, data, reset };
}

export default usePostAgent;
